### ISSUE TITLE
Help me @jwarby

### ISSUE THREAD

**Issue by dona12345** [jwarby/3ds-to-pc-controller#3]
I want to continue rd3ds as in my branch,but i don't know how to add 3ds buttons as keys from Windows,can you help me?

**Comment by jwarby** [comment]
Hi @dona12345.  I'm afraid I don't anything about rd3ds, nor mapping of Windows keys.  This is just a toy project and will probably not be of any use to you sorry.  Thanks.

**Comment by ImmutableOctet** [comment]
@dona12345 '[SendInput](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646310%28v=vs.85%29.aspx)' would be your best bet. I wrote my own 3DS-controller software awhile ago, so you can [use that as a reference](https://github.com/ImmutableOctet/3ds-controller/blob/2e991be8c28dab4e91239fd60009d4dbc9b800d5/3DS_Input_Listener/Listener.cpp#L233).
